[containment]
score_type = "Language Borrowing"
threshold = 0.6
comparator = "lt"
feedback = [
    "You need to rely less on the language in the text and focus more on rewriting the key ideas.",
    "You did a good job of using your own language to describe the main ideas of the text.",
]

[containment_chat]
score_type = "Language Borrowing (from iTELL AI)"
threshold = 0.6
comparator = "lt"
feedback = [
    "You need to depend less on the examples provided by iTELL AI.",
    "You did a good job of using your own language to describe the main ideas of the text.",
]

[similarity]
score_type = "Relevance"
threshold = 0.5
comparator = "gt"
feedback = [
    "To be successful, you need to stay on topic. Find the main ideas of the text and focus your summary on those ideas.",
    "You did a good job of staying on topic and writing about the main ideas of the text.",
]

[content]
score_type = "Content"
threshold = -0.20 # AugustaTech initial value is `-0.20`
comparator = "gt"
feedback = [
    "You need to include more key ideas and details from the page to successfully summarize the content. Consider focusing on the main ideas of the text and providing support for those ideas in your summary.",
    "You did a good job of including key ideas and details on this page.",
]

[language]
score_type = "Language"
threshold = 2.0
comparator = "gt"
feedback = [
    "Your summary shows a very basic understanding of lexical and syntactic structures.",
    "Your summary shows an appropriate range of lexical and syntactic structures.",
    "Your summary shows an excellent range of lexical and syntactic structures.",
    "Your summary shows an excellent range of lexical and syntactic structures.",
]

[english]
score_type = "English"
threshold = true
comparator = "eq"
feedback = ["Please write your summary in English.", ""]

[profanity]
score_type = "Profanity"
threshold = false
comparator = "eq"
feedback = ["Please avoid using inappropriate language in your summary.", ""]
