kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: logs-hostpath
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /var/log/itell-ai
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itell-ai-logs
  namespace: jhub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: logs-hostpath
  resources:
    requests:
      storage: 1Gi
