kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: models-nfs
  labels:
    vol: models-pvc
  namespace: jhub
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
